# Add application configuration variables here, as shown below.
#
# PUSHER_APP_ID: "2954"
# PUSHER_KEY: 7381a978f7dd7f9a1117
# PUSHER_SECRET: abdc3b896a0ffb85d373
# STRIPE_API_KEY: EdAvEPVEC3LuaTg5Q3z6WbDVqZlcBQ8Z
# STRIPE_PUBLIC_KEY: pk_BRgD57O8fHja9HxduJUszhef6jCyS
GOOGLE_API_DEV: AIzaSyAO9Z0tWf75CNdw0ADDoB6MrnX4dm5sRKM
GOOGLE_API_TEST: AIzaSyBY3muwdlmMehKIDcPZTiNzBhlwmF6i9_c
GOOGLE_API_STAGING: AIzaSyDkB4eO86DxOAR0mTq_VDj8zVkBdhhGjjQ
GOOGLE_API_PRODUCTION: AIzaSyB4oIpNJi8mImqM1dhkpD8mx6D_xCTWR9Y
